const state={lastSync:null,portfolio:{value:0,options:0,buyingPower:0},positions:[],watch:[]};
const meta={dashboard:["Dashboard","Your trading workspace at a glance."],portfolio:["Portfolio","Positions, exposure, and account snapshot."],watchlists:["Watchlists","Organize ideas before they become trades."],premarket:["Pre-Market","Prepare the plan before the session starts."],journal:["Journal","Track the thesis, execution, and result."],rules:["Rules","Your guardrails for disciplined trading."],training:["Training","Build market and options understanding step by step."]};
function money(v){return "$"+Number(v||0).toFixed(2)}
function sync(){fetch("data/dashboard.json").then(r=>r.ok?r.json():Promise.reject()).then(d=>{Object.assign(state,d,{lastSync:new Date()});renderCurrent()}).catch(()=>{state.lastSync=null;renderCurrent()})}
function rows(){return state.positions.length?state.positions.map(p=>'<div class="row"><div><b>'+p.symbol+' '+(p.description||"")+'</b><span class="sub">Qty '+p.quantity+' · Cost '+money(p.averagePrice)+' · Mark '+money(p.markPrice)+'</span></div><strong class="'+(p.pnl>=0?"green":"red")+'">'+money(p.pnl)+'</strong></div>').join(""):'<div class="empty">No live positions available.</div>'}
const views={
dashboard:()=>'<div class="grid"><div class="card"><div class="label">Portfolio value</div><div class="big">'+money(state.portfolio.value)+'</div><span class="sub">Live sync</span></div><div class="card"><div class="label">Options value</div><div class="big">'+money(state.portfolio.options)+'</div><span class="sub">Current option exposure</span></div><div class="card"><div class="label">Buying power</div><div class="big">'+money(state.portfolio.buyingPower)+'</div><span class="sub">Broker-reported</span></div><div class="card"><div class="label">Open positions</div><div class="big">'+state.positions.length+'</div><span class="sub">Live positions</span></div></div><div class="split"><div class="card"><h2>Open positions</h2>'+rows()+'</div><div class="card"><h2>Data connection</h2><p class="note">'+(state.lastSync?'Last sync '+state.lastSync.toLocaleTimeString():'Waiting for live broker adapter.')+'</p><button class="action" onclick="sync()">Refresh data</button></div></div>',
portfolio:()=>'<div class="card"><h2>Portfolio</h2><table class="table"><tr><th>Position</th><th>Qty</th><th>Cost</th><th>Mark</th><th>P/L</th><th>Expiry</th></tr>'+state.positions.map(p=>'<tr><td><b>'+p.symbol+'</b><span class="sub">'+(p.description||"")+'</span></td><td>'+p.quantity+'</td><td>'+money(p.averagePrice)+'</td><td>'+money(p.markPrice)+'</td><td class="'+(p.pnl>=0?"green":"red")+'">'+money(p.pnl)+'</td><td>'+(p.expiration||"—")+'</td></tr>').join("")+'</table></div>',
watchlists:()=>'<div class="card"><h2>Watchlists</h2><table class="table"><tr><th>Ticker</th><th>Theme</th><th>Status</th></tr>'+state.watch.map(x=>'<tr><td><b>'+x.symbol+'</b></td><td>'+x.theme+'</td><td><span class="pill">'+x.status+'</span></td></tr>').join("")+'</table></div>',
premarket:()=>'<div class="split"><div class="card"><h2>Pre-market checklist</h2><div class="rule">✓ Review overnight news and catalysts</div><div class="rule">✓ Check futures, sectors, and volume</div><div class="rule">✓ Recheck option spreads and liquidity</div><div class="rule">✓ Define entries, exits, and maximum loss</div></div><div class="card"><h2>Live data</h2><p class="note">Use Refresh Data after the broker adapter is connected.</p></div></div>',
journal:()=>'<div class="card"><h2>Trade Journal</h2><p class="note">Document the thesis before entry and the result after exit.</p>'+rows()+'</div>',
rules:()=>'<div class="card"><h2>Trading Rules</h2><div class="rule"><b>01 · Know maximum loss</b><span class="sub">Options can expire worthless; size accordingly.</span></div><div class="rule"><b>02 · Have an exit before entry</b><span class="sub">Use price, thesis, and time-based exits.</span></div><div class="rule"><b>03 · Understand exercise</b><span class="sub">A standard equity option represents 100 shares.</span></div><div class="rule"><b>04 · Journal every trade</b><span class="sub">Track what was known at the time.</span></div></div>',
training:()=>'<div class="training">'+[["01","Calls & puts","Strike, expiration, premium, intrinsic and time value."],["02","Greeks","Delta, theta, gamma, and vega."],["03","Risk","Position sizing and maximum loss."],["04","Execution","Bid/ask spreads, limits, liquidity."],["05","Analysis","Support, resistance, volume, catalysts."],["06","Review","Turn completed trades into feedback."]].map(x=>'<div class="card lesson"><span class="pill">'+x[0]+'</span><h3>'+x[1]+'</h3><p class="note">'+x[2]+'</p></div>').join('')+'</div>'};
function renderCurrent(){const tab=document.querySelector("nav button.active")?.dataset.tab||"dashboard";document.getElementById("content").innerHTML=views[tab]()}
function show(tab){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));document.getElementById("title").textContent=meta[tab][0];document.getElementById("sub").textContent=meta[tab][1];renderCurrent()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.tab));show("dashboard");sync();